### PR TITLE
fix maps and add test to check maps are correct against the 100 seeds

### PR DESCRIPTION
**Pull request by StoneT2000**
there appears to probably be a bug with RNG, not your map implementation, but this test is working now it seems.

### CODE REVIEW

**Comment by StoneT2000** [comment]
Run `python -m unittest luxai2021.tests.test_map.TestMap.test_map_gen_valid` to test. It generated two maps correctly at the moment, seed 10002 it doesn't

**Comment by royerk** [comment]
That *must* be why my training is great but my public score is below 0 ;)

**Comment by StoneT2000** [comment]
looks like the config has a default map size of 32 and it seems to be fixed to that? @glmcdona

**Review by glmcdona — APPROVED** [review]

**Comment by glmcdona** [comment]
Awesome, thanks @StoneT2000!

@royerk, also have a look at this line used in inference:
https://github.com/glmcdona/LuxPythonEnvGym/blob/df464cc38b22aed393e449b2426fff4217e2d442/examples/agent_policy.py#L530

Try modifying both to be `deterministic=False` to see if you get more closer to your expected result in inference mode. In inference mode, it doesn't randomly perturbate the actions since it doesn't need to explore. Some solutions converge to weird solutions that will just repeatedly do an invalid action, relying on this randomness to explore. I don't think this map change is likely to change the result of your model significantly.

**Comment by royerk** [comment]
@glmcdona shouldn't it be merged then?

**Comment by glmcdona** [comment]
My bad, merged!

**Pull request merged**
